import sqlite3
from text_to_sql_engine import generate_sql_from_gemini, extract_sql

def run_query(user_input):
    # 1. Get the SQL from our AI Engine
    raw_ai_response = generate_sql_from_gemini(user_input)
    sql_query = extract_sql(raw_ai_response)
    
    # 2. Connect to the database generated by your data_engine.py
    db_name = 'transactions.db'

    print(f"\n🚀 Executing SQL on {db_name}:\n{sql_query}\n")

    try:
        conn = sqlite3.connect(db_name)
        cursor = conn.cursor()
        if sql_query.lower().startswith("sqlite"):
           sql_query = sql_query[6:].strip()
        sql_query = sql_query.replace("```sql", "") \
                     .replace("```sqlite", "") \
                     .replace("```", "") \
                     .strip()
        cursor.execute(sql_query)
        results = cursor.fetchall()
        
        # Get column names for better display
        column_names = [description[0] for description in cursor.description]
        
        print("📊 RESULTS:")
        print("-" * 30)
        print(column_names)
        for row in results:
            print(row)
        print("-" * 30)
        
        conn.close()
    except Exception as e:
        print(f"❌ Database Error: {e}")

if __name__ == "__main__":
    print("--- InsightX Analytics Real-Time SQL Engine ---")
    question = input("🔍 Ask a question about your transactions: ")
    run_query(question)
