import sqlite3
from text_to_sql_engine import generate_sql_from_gemini, extract_sql_and_insight

# def run_query(user_input):
#     # 1. Get the SQL from our AI Engine
#     raw_ai_response = generate_sql_from_gemini(user_input)
#     sql_query = extract_sql(raw_ai_response)
    
#     # 2. Connect to the database generated by your data_engine.py
#     db_name = 'transactions.db'

#     print(f"\n🚀 Executing SQL on {db_name}:\n{sql_query}\n")

#     try:
#         conn = sqlite3.connect(db_name)
#         cursor = conn.cursor()
#         if sql_query.lower().startswith("sqlite"):
#            sql_query = sql_query[6:].strip()
#         sql_query = sql_query.replace("```sql", "") \
#                      .replace("```sqlite", "") \
#                      .replace("```", "") \
#                      .strip()
#         cursor.execute(sql_query)
#         results = cursor.fetchall()
        
#         # Get column names for better display
#         column_names = [description[0] for description in cursor.description]
        
#         print("📊 RESULTS:")
#         print("-" * 30)
#         print(column_names)
#         for row in results:
#             print(row)
#         print("-" * 30)
        
#         conn.close()
#     except Exception as e:
#         print(f"❌ Database Error: {e}")

import re

def autocorrect_insight(insight, sql_query, results):
    """
    Replaces numeric values in AI insight with actual database result
    for aggregate queries like MIN, MAX, AVG, COUNT, SUM.
    """

    if not results or not results[0]:
        return insight

    actual_value = results[0][0]

    # If query contains aggregate functions
    if any(keyword in sql_query.upper() for keyword in ["MIN(", "MAX(", "AVG(", "COUNT(", "SUM("]):

        # Replace first number found in insight
        corrected_insight = re.sub(r"\d+(\.\d+)?", str(actual_value), insight, count=1)

        return corrected_insight

    return insight

def run_query(user_input):

    raw_ai_response = generate_sql_from_gemini(user_input)

    insight, sql_query = extract_sql_and_insight(raw_ai_response)

    db_name = 'transactions.db'

    print("\n🧠 AI INSIGHT:")
    print("-" * 40)
    print(insight)
    print("-" * 40)

    print("\n📜 GENERATED SQL:")
    print("-" * 40)
    print(sql_query)
    print("-" * 40)

    
    conn = sqlite3.connect(db_name)
    cursor = conn.cursor()

    cursor.execute(sql_query)
    results = cursor.fetchall()
    columns = [description[0] for description in cursor.description]

    # ✅ Auto-correct insight BEFORE printing
    insight = autocorrect_insight(insight, sql_query, results)

    print("\n🧠 AI INSIGHT (Verified):")
    print("-" * 40)
    print(insight)
    print("-" * 40)
    print("\n📜 GENERATED SQL:")
    print("-" * 40)
    print(sql_query)
    print("-" * 40)

    print("\n📊 QUERY RESULTS:")
    print("-" * 40)
    if results:
        for row in results:
            for col, value in zip(columns, row):
                print(f"{col}: {value}")
    else:
        print("No results found.")


if __name__ == "__main__":
    print("--- InsightX Analytics Real-Time SQL Engine ---")
    question = input("🔍 Ask a question about your transactions: ")
    run_query(question)
